# Generated by Django 4.2.19 on 2025-02-18 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CLIENT', 'Client'), ('GESTIONNAIRE', 'Gestionnaire'), ('ADMIN', 'Administrateur')], default='CLIENT', max_length=20),
        ),
    ]
