# Generated by Django 4.2.19 on 2025-02-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=100)),
                ('modele', models.CharField(max_length=100)),
                ('annee', models.IntegerField()),
                ('kilometrage', models.IntegerField()),
                ('prix_vente', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('prix_location', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('type_offre', models.CharField(choices=[('VENTE', 'À vendre'), ('LOCATION', 'À louer')], max_length=20)),
                ('etat', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('RESERVE', 'Réservé'), ('VENDU', 'Vendu'), ('LOUE', 'Loué')], max_length=20)),
                ('description', models.TextField()),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'vehicules',
            },
        ),
    ]
