# Generated by Django 4.2.19 on 2025-02-12 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('mileage', models.IntegerField()),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('rental_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('type_offer', models.CharField(choices=[('SALE', 'À vendre'), ('RENTAL', 'À louer')], max_length=20)),
                ('state', models.CharField(choices=[('AVAILABLE', 'Disponible'), ('RESERVED', 'Réservé'), ('SOLD', 'Vendu'), ('RENTED', 'Loué')], max_length=20)),
                ('description', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'vehicles',
            },
        ),
    ]
